name: deep-rl
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.6
  - pip
pip:
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - ipykernel
  - nb_conda
  - gym
  - gym-atari
  - matplotlib
  - tqdm
  - tk